Repository cssconf/2019.cssconf.eu, pull requests merged in 2019-05, with the labels that each got.

#119 Add BIPoCiT Speakers page
  .gitignore
  contents/bipocit-space-speakers.json
  scripts/spreadsheet-import/index.js
  templates/pages/bipocit-space-speakers.html.njk
Labels: enhancement, prio-high

#131 Use new Schedule design
  contents/css/_base.grid.css
  contents/css/_components.intro.css
  contents/css/_components.schedule-item-events.css
  contents/css/_components.schedule-item.css
  contents/css/_components.schedule.css
  contents/css/main.css
  templates/pages/schedule.html.njk
Labels: enhancement, prio-high

#139 Add venue schedule
  .gitignore
  contents/css/_settings.typography.css
  contents/schedule-venue.json
  plugins/nunjucks.js
  scripts/spreadsheet-import/index.js
  scripts/spreadsheet-import/process-schedule.js
  templates/pages/schedule-venue.html.njk
Labels: design-needed, enhancement, prio-high

#142 Fix speakers gallery progress bar
  contents/css/_components.speakers-gallery.css
Labels: bug

#147 Add additional tracks to the schedule
  scripts/spreadsheet-import/process-schedule.js
Labels: enhancement, prio-high

#146 Add styles to /schedule/venue
  scripts/spreadsheet-import/process-schedule.js
  templates/pages/schedule-venue.html.njk
Labels: enhancement, prio-high
